### ISSUE TITLE
streamingへ接続する際にUserAgentを通知していない？

### ISSUE THREAD

**Issue by takayamaki** [cucmberium/TootNet#2]
お世話になります、[imastodon.net](https://imastodon.net/)を運営しておりますフサギコと申します。

アイマストドンでは不審なアクセスがないか、アクセスログをたまに浚っているのですが、`/api/v1/streaming` 以下のアクセスにおいて、UserAgentの通知がないServerSideEventsアクセスがあることに気付きました。

同時間帯同IPアドレスからの他アクセスから推定するにこちらのライブラリを用いたアクセスではないかと思い、報告させていただきます。
もし違っていた場合には申し訳ありません。

インスタンス運営者としてはUserAgentの通知がないアクセスは少々驚いてしまいますので、お手すきの際に実装をお願いできれば幸いです。

宜しくお願いいたします。

![image](https://user-images.githubusercontent.com/24884114/33792908-015014c0-dcf0-11e7-8ae8-a582345b3a6f.png)

**Comment by cucmberium** [comment]
TootNetでは以下のようにStreaming時でもUserAgentが付与されるようになっています。
https://github.com/cucmberium/TootNet/blob/master/TootNet/Streaming/Streaming.cs#L143
https://github.com/cucmberium/TootNet/blob/master/TootNet/Connection.cs#L30

このバグはTootNetの問題ではなく私の作っているFlantterでのバグだと思われます。
Flantterのリポジトリにissueを立てておきますのでそちらを確認ください。
