### ISSUE TITLE
ハッシュタグのstreamingに接続する際、タグ文字列の空チェックを行っていない？

### ISSUE THREAD

**Issue by takayamaki** [cucmberium/TootNet#3]
お世話になります、imastodon.netのフサギコです。

#2 にも関連することですが、下記のアクセスログから見るに、ハッシュタグのstreamingに接続する際に_parameters["tag"]が空文字列となってしまっていないかのチェックが行われていないように見受けられます。
https://github.com/cucmberium/TootNet/blob/master/TootNet/Streaming/Streaming.cs#L120

私が手元で確認したところ、ハッシュタグの指定が空文字列だった場合、keepalive用の文字列である":thump"のみが送信されてくる状態となるようです。

私の手元に.NETの開発環境がないためIssueを立てるのみで申し訳ありませんが、こちらについても併せてご確認いただけますと幸いです。
宜しくお願いいたします。

![image](https://user-images.githubusercontent.com/24884114/33792908-015014c0-dcf0-11e7-8ae8-a582345b3a6f.png)

**Comment by cucmberium** [comment]
644929386af71d278f4164e602cfe50fb332ee91 にて対応いたしました。
報告ありがとうございます。
